finished protoypes and classes
nolbir-io/en.javascript.info pull request #5
Opened 2023-05-02 11:28 UTC by iroda743

2023-05-12 10:59 UTC, mredem96 commented on 1-js/08-prototypes/02-function-prototype/article.md
> +JavaScript boshidayoq prototip merosga ega edi. Bu dasturlash tilining asosiy xususiyatlaridan biri hisoblanadi.
inheritence bu yerda metaphore

2023-06-18 16:59 UTC, mredem96 requested changes

2023-07-02 16:08 UTC, mredem96 commented on 1-js/09-classes/01-class/article.md
> +Sinf maydonlari boshqa sintaksisni taqdim etadi:
sinf -> class

2023-07-13 10:52 UTC, nolbirtech submitted a review, later dismissed

2023-07-17 03:24 UTC, Asliddin2002 requested changes

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Yuqorida ko'rsatilgan `(*)` belgisi `animal``rabbit` ning prototipi bo'lishini belgilaydi.
Yuqorida ko'rsatilgan `(*)` belgisi bor yo'ldagi kod `animal` obyekti `rabbit` ning prototipi bo'lishini belgilaydi

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> + Keyin  `alert` esa `rabbit.eats` `(**)` ma'lumotini o'qishga harakat qiladi, ammo u `rabbit` ichida mavjud emas, shuning uchun JavaScript `[[Prototype]]` havolasiga amal qiladi va uni `animal`ichida
"havolasiga" ni o'rniga "qoidasiga" yoki "tavsiyasiga" qo'ysak?

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Agar bizda `animal` metodi mavjud bo'lsa, biz uni `rabbit` deb nomlashimiz mumkin:
Agar `animal` obyektida metod ham mavjud bo'lsa, biz uni `rabbit` obyektidan chaqirishimiz mumkin:

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Ushbu metod avtomatik tarzda prototipdan olinadi, misol uchun:
Ushbu metod avtomatik tarzda prototipdan misoldagidek (yoki "xuddi shunaqa") olinadi.

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Endi biz `longEar`dan nimadir o'qimoqchi bo'lsak, ammo biz qidirgan ma'lumot mavjud bo'lmasa, JavaScript uni avval `rabbit` dan, keyin esa `longEar`dan izlab ko'radi.
Endi biz `longEar` obyektidan dan nimadir o'qimoqchi bo'lsak, ammo biz qidirgan ma'lumot mavjud bo'lmasa, JavaScript uni avval `rabbit` dan, keyin esa `animal`dan izlab ko'radi.

2023-07-17 03:24 UTC, Asliddin2002 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +1. Havolalar aylana bo'ylab bora olmaydi. Agar biz aylanada `__proto__` ni belgilashga harakat qilsak, JavaScript bu harakatning xato ekanligini ko'rsatadi.
sal chalkash.

2023-12-14 07:23 UTC, mredem96 approved these changes

2023-12-14 07:23 UTC, mredem96 approved these changes

2023-12-14 07:24 UTC, merged